name: Go
on:
  push:
    tags-ignore:
      - "v*"
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: CI
      run: make ci
